## AUTO-GENERATED by tools/gen_room_prop_catalog.py — do not edit by hand.
## Room prop ID table: VoxelMaterial.PROP_FIRST + index.
class_name RoomPropCatalog
extends RefCounted

const PROP_MESH_DIR := "res://assets/city/props/"
const PROP_FIRST := 75
const PROP_COUNT := 105
const PROP_LAST := 179

## stem, family, walk_through, aabb(x,y,z,sx,sy,sz)
const ENTRIES: Array[Dictionary] = [
	{"stem": "crate", "family": "wood", "walk_through": false, "aabb": Vector3(0.1397, 0.0500, 0.1397), "aabb_size": Vector3(0.7206, 0.9200, 0.7206)},
	{"stem": "barrel", "family": "wood", "walk_through": false, "aabb": Vector3(0.1200, 0.0400, 0.1200), "aabb_size": Vector3(0.7600, 0.9000, 0.7600)},
	{"stem": "chair", "family": "wood", "walk_through": false, "aabb": Vector3(0.2885, 0.0500, 0.2885), "aabb_size": Vector3(0.4230, 0.9200, 0.4230)},
	{"stem": "bathroomCabinet", "family": "wood", "walk_through": false, "aabb": Vector3(0.2146, 0.0500, 0.3300), "aabb_size": Vector3(0.5708, 0.9200, 0.3400)},
	{"stem": "bathroomMirror", "family": "ceramic", "walk_through": false, "aabb": Vector3(0.1680, 0.0500, 0.3305), "aabb_size": Vector3(0.6640, 0.9200, 0.3390)},
	{"stem": "bathroomSink", "family": "ceramic", "walk_through": false, "aabb": Vector3(0.2068, 0.0500, 0.2470), "aabb_size": Vector3(0.5864, 0.9200, 0.5061)},
	{"stem": "bathtub", "family": "ceramic", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2682), "aabb_size": Vector3(0.9400, 0.3376, 0.4635)},
	{"stem": "bear", "family": "wood", "walk_through": true, "aabb": Vector3(0.0903, 0.0500, 0.2325), "aabb_size": Vector3(0.8194, 0.9200, 0.5350)},
	{"stem": "bedBunk", "family": "fabric", "walk_through": false, "aabb": Vector3(0.2453, 0.0500, 0.0300), "aabb_size": Vector3(0.5093, 0.7186, 0.9400)},
	{"stem": "bedDouble", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0976, 0.0500, 0.0300), "aabb_size": Vector3(0.8048, 0.3200, 0.9400)},
	{"stem": "bedSingle", "family": "fabric", "walk_through": false, "aabb": Vector3(0.2516, 0.0500, 0.0300), "aabb_size": Vector3(0.4968, 0.3200, 0.9400)},
	{"stem": "bench", "family": "wood", "walk_through": false, "aabb": Vector3(0.0970, 0.0500, 0.2885), "aabb_size": Vector3(0.8060, 0.9200, 0.4230)},
	{"stem": "benchCushion", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0887, 0.0500, 0.2843), "aabb_size": Vector3(0.8226, 0.9200, 0.4313)},
	{"stem": "benchCushionLow", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2443), "aabb_size": Vector3(0.9400, 0.4486, 0.5114)},
	{"stem": "bookcaseClosed", "family": "wood", "walk_through": false, "aabb": Vector3(0.2682, 0.0500, 0.3476), "aabb_size": Vector3(0.4635, 0.9200, 0.3047)},
	{"stem": "bookcaseClosedDoors", "family": "wood", "walk_through": false, "aabb": Vector3(0.2682, 0.0500, 0.3476), "aabb_size": Vector3(0.4635, 0.9200, 0.3047)},
	{"stem": "bookcaseClosedWide", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3394), "aabb_size": Vector3(0.9400, 0.9088, 0.3213)},
	{"stem": "bookcaseOpen", "family": "wood", "walk_through": false, "aabb": Vector3(0.2755, 0.0500, 0.3522), "aabb_size": Vector3(0.4491, 0.9200, 0.2957)},
	{"stem": "bookcaseOpenLow", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1988), "aabb_size": Vector3(0.9400, 0.9200, 0.6025)},
	{"stem": "books", "family": "wood", "walk_through": true, "aabb": Vector3(0.0300, 0.0500, 0.1973), "aabb_size": Vector3(0.9400, 0.6416, 0.6053)},
	{"stem": "cabinetBed", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1163), "aabb_size": Vector3(0.9400, 0.8090, 0.7674)},
	{"stem": "cabinetBedDrawer", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1124), "aabb_size": Vector3(0.9400, 0.9105, 0.7752)},
	{"stem": "cabinetBedDrawerTable", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1124), "aabb_size": Vector3(0.9400, 0.9105, 0.7752)},
	{"stem": "cabinetTelevision", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3394), "aabb_size": Vector3(0.9400, 0.3688, 0.3213)},
	{"stem": "cabinetTelevisionDoors", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3337), "aabb_size": Vector3(0.9400, 0.3688, 0.3325)},
	{"stem": "cardboardBoxOpen", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2229), "aabb_size": Vector3(0.9400, 0.7001, 0.5543)},
	{"stem": "ceilingFan", "family": "metal", "walk_through": false, "aabb": Vector3(0.0903, 0.0500, 0.0300), "aabb_size": Vector3(0.8194, 0.2492, 0.9400)},
	{"stem": "chairCushion", "family": "fabric", "walk_through": false, "aabb": Vector3(0.2843, 0.0500, 0.2843), "aabb_size": Vector3(0.4313, 0.9200, 0.4313)},
	{"stem": "chairDesk", "family": "wood", "walk_through": false, "aabb": Vector3(0.2319, 0.0500, 0.2472), "aabb_size": Vector3(0.5361, 0.9200, 0.5056)},
	{"stem": "chairRounded", "family": "wood", "walk_through": false, "aabb": Vector3(0.2822, 0.0500, 0.2822), "aabb_size": Vector3(0.4356, 0.9200, 0.4356)},
	{"stem": "coatRack", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3450), "aabb_size": Vector3(0.9400, 0.5825, 0.3100)},
	{"stem": "coatRackStanding", "family": "wood", "walk_through": false, "aabb": Vector3(0.3206, 0.0500, 0.3206), "aabb_size": Vector3(0.3589, 0.9200, 0.3589)},
	{"stem": "computerKeyboard", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2915), "aabb_size": Vector3(0.9400, 0.1079, 0.4169)},
	{"stem": "computerMouse", "family": "metal", "walk_through": false, "aabb": Vector3(0.2172, 0.0500, 0.0300), "aabb_size": Vector3(0.5656, 0.2693, 0.9400)},
	{"stem": "computerScreen", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3608), "aabb_size": Vector3(0.9400, 0.6945, 0.2784)},
	{"stem": "desk", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2396), "aabb_size": Vector3(0.9400, 0.4910, 0.5207)},
	{"stem": "deskCorner", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.3750, 0.9400)},
	{"stem": "dryer", "family": "metal", "walk_through": false, "aabb": Vector3(0.1066, 0.0500, 0.1162), "aabb_size": Vector3(0.7868, 0.9200, 0.7677)},
	{"stem": "kitchenBar", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2602), "aabb_size": Vector3(0.9400, 0.8991, 0.4795)},
	{"stem": "kitchenBarEnd", "family": "wood", "walk_through": false, "aabb": Vector3(0.3712, 0.0500, 0.2550), "aabb_size": Vector3(0.2576, 0.9200, 0.4900)},
	{"stem": "kitchenBlender", "family": "metal", "walk_through": false, "aabb": Vector3(0.2114, 0.0500, 0.2642), "aabb_size": Vector3(0.5773, 0.9200, 0.4716)},
	{"stem": "kitchenCabinet", "family": "wood", "walk_through": false, "aabb": Vector3(0.0500, 0.0500, 0.0300), "aabb_size": Vector3(0.9000, 0.9200, 0.9400)},
	{"stem": "kitchenCabinetCornerInner", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.9004, 0.9400)},
	{"stem": "kitchenCabinetCornerRound", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.9200, 0.9400)},
	{"stem": "kitchenCabinetDrawer1", "family": "wood", "walk_through": false, "aabb": Vector3(0.0500, 0.0500, 0.0300), "aabb_size": Vector3(0.9000, 0.9200, 0.9400)},
	{"stem": "kitchenCabinetDrawer", "family": "wood", "walk_through": false, "aabb": Vector3(0.0698, 0.0500, 0.1748), "aabb_size": Vector3(0.8603, 0.9200, 0.6505)},
	{"stem": "kitchenCabinetUpper", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2498), "aabb_size": Vector3(0.9400, 0.8363, 0.5005)},
	{"stem": "kitchenCabinetUpperCorner", "family": "wood", "walk_through": false, "aabb": Vector3(0.2319, 0.0500, 0.2377), "aabb_size": Vector3(0.5362, 0.9200, 0.5246)},
	{"stem": "kitchenCabinetUpperDouble", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2498), "aabb_size": Vector3(0.9400, 0.8363, 0.5005)},
	{"stem": "kitchenCabinetUpperLow", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2498), "aabb_size": Vector3(0.9400, 0.4281, 0.5005)},
	{"stem": "kitchenCoffeeMachine", "family": "metal", "walk_through": false, "aabb": Vector3(0.1249, 0.0500, 0.0300), "aabb_size": Vector3(0.7503, 0.6851, 0.9400)},
	{"stem": "kitchenFridge", "family": "metal", "walk_through": false, "aabb": Vector3(0.2697, 0.0500, 0.3372), "aabb_size": Vector3(0.4607, 0.9200, 0.3256)},
	{"stem": "kitchenFridgeBuiltIn", "family": "metal", "walk_through": false, "aabb": Vector3(0.2573, 0.0500, 0.2469), "aabb_size": Vector3(0.4855, 0.9200, 0.5062)},
	{"stem": "kitchenFridgeSmall", "family": "metal", "walk_through": false, "aabb": Vector3(0.1576, 0.0500, 0.2611), "aabb_size": Vector3(0.6847, 0.9200, 0.4777)},
	{"stem": "kitchenMicrowave", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1231), "aabb_size": Vector3(0.9400, 0.5786, 0.7538)},
	{"stem": "kitchenSink", "family": "ceramic", "walk_through": false, "aabb": Vector3(0.0851, 0.0500, 0.0667), "aabb_size": Vector3(0.8298, 0.9200, 0.8665)},
	{"stem": "kitchenStove", "family": "metal", "walk_through": false, "aabb": Vector3(0.0500, 0.0500, 0.0300), "aabb_size": Vector3(0.9000, 0.9200, 0.9400)},
	{"stem": "kitchenStoveElectric", "family": "metal", "walk_through": false, "aabb": Vector3(0.0500, 0.0500, 0.0300), "aabb_size": Vector3(0.9000, 0.9200, 0.9400)},
	{"stem": "lampRoundFloor", "family": "metal", "walk_through": true, "aabb": Vector3(0.4004, 0.0500, 0.3881), "aabb_size": Vector3(0.1991, 0.9200, 0.2237)},
	{"stem": "lampRoundTable", "family": "metal", "walk_through": true, "aabb": Vector3(0.2623, 0.0500, 0.2286), "aabb_size": Vector3(0.4754, 0.9200, 0.5428)},
	{"stem": "lampSquareCeiling", "family": "metal", "walk_through": true, "aabb": Vector3(0.2452, 0.0500, 0.2452), "aabb_size": Vector3(0.5096, 0.9200, 0.5096)},
	{"stem": "lampSquareFloor", "family": "metal", "walk_through": true, "aabb": Vector3(0.4172, 0.0500, 0.4172), "aabb_size": Vector3(0.1656, 0.9200, 0.1656)},
	{"stem": "lampSquareTable", "family": "metal", "walk_through": true, "aabb": Vector3(0.2938, 0.0500, 0.2938), "aabb_size": Vector3(0.4124, 0.9200, 0.4124)},
	{"stem": "laptop", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0708), "aabb_size": Vector3(0.9400, 0.5716, 0.8584)},
	{"stem": "loungeChair", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1035), "aabb_size": Vector3(0.9400, 0.8649, 0.7931)},
	{"stem": "loungeChairRelax", "family": "wood", "walk_through": false, "aabb": Vector3(0.1532, 0.0500, 0.0300), "aabb_size": Vector3(0.6936, 0.8604, 0.9400)},
	{"stem": "loungeSofa", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2917), "aabb_size": Vector3(0.9400, 0.4424, 0.4165)},
	{"stem": "loungeSofaCorner", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.4424, 0.9400)},
	{"stem": "loungeSofaLong", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1035), "aabb_size": Vector3(0.9400, 0.4424, 0.7931)},
	{"stem": "loungeSofaOttoman", "family": "fabric", "walk_through": false, "aabb": Vector3(0.0402, 0.0500, 0.0300), "aabb_size": Vector3(0.9197, 0.4800, 0.9400)},
	{"stem": "pillow", "family": "fabric", "walk_through": true, "aabb": Vector3(0.0300, 0.0500, 0.3069), "aabb_size": Vector3(0.9400, 0.8893, 0.3862)},
	{"stem": "pillowLong", "family": "fabric", "walk_through": true, "aabb": Vector3(0.0300, 0.0500, 0.3770), "aabb_size": Vector3(0.9400, 0.5372, 0.2460)},
	{"stem": "plantSmall1", "family": "foliage", "walk_through": true, "aabb": Vector3(0.1757, 0.0500, 0.1757), "aabb_size": Vector3(0.6485, 0.9200, 0.6485)},
	{"stem": "plantSmall2", "family": "foliage", "walk_through": true, "aabb": Vector3(0.1757, 0.0500, 0.1757), "aabb_size": Vector3(0.6485, 0.9200, 0.6485)},
	{"stem": "plantSmall3", "family": "foliage", "walk_through": true, "aabb": Vector3(0.1759, 0.0500, 0.2166), "aabb_size": Vector3(0.6483, 0.9200, 0.5668)},
	{"stem": "pottedPlant", "family": "foliage", "walk_through": true, "aabb": Vector3(0.3341, 0.0500, 0.3139), "aabb_size": Vector3(0.3318, 0.9200, 0.3723)},
	{"stem": "radio", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3407), "aabb_size": Vector3(0.9400, 0.6720, 0.3186)},
	{"stem": "rugRectangle", "family": "fabric", "walk_through": true, "aabb": Vector3(0.0300, 0.0500, 0.2163), "aabb_size": Vector3(0.9400, 0.0500, 0.5674)},
	{"stem": "rugRound", "family": "fabric", "walk_through": true, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.0500, 0.9400)},
	{"stem": "rugRounded", "family": "fabric", "walk_through": true, "aabb": Vector3(0.0300, 0.0500, 0.2163), "aabb_size": Vector3(0.9400, 0.0500, 0.5674)},
	{"stem": "rugSquare", "family": "fabric", "walk_through": true, "aabb": Vector3(0.0377, 0.0500, 0.0300), "aabb_size": Vector3(0.9247, 0.0500, 0.9400)},
	{"stem": "shower", "family": "ceramic", "walk_through": false, "aabb": Vector3(0.2489, 0.0500, 0.2407), "aabb_size": Vector3(0.5022, 0.9200, 0.5186)},
	{"stem": "sideTable", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2948), "aabb_size": Vector3(0.9400, 0.6673, 0.4105)},
	{"stem": "sideTableDrawers", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2928), "aabb_size": Vector3(0.9400, 0.6673, 0.4143)},
	{"stem": "speaker", "family": "metal", "walk_through": false, "aabb": Vector3(0.3753, 0.0500, 0.3753), "aabb_size": Vector3(0.2493, 0.9200, 0.2493)},
	{"stem": "speakerSmall", "family": "metal", "walk_through": false, "aabb": Vector3(0.2565, 0.0500, 0.2788), "aabb_size": Vector3(0.4870, 0.9200, 0.4423)},
	{"stem": "stoolBar", "family": "wood", "walk_through": false, "aabb": Vector3(0.2054, 0.0500, 0.2422), "aabb_size": Vector3(0.5892, 0.9200, 0.5156)},
	{"stem": "stoolBarSquare", "family": "wood", "walk_through": false, "aabb": Vector3(0.3094, 0.0500, 0.3160), "aabb_size": Vector3(0.3811, 0.9200, 0.3681)},
	{"stem": "table", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2408), "aabb_size": Vector3(0.9400, 0.3695, 0.5185)},
	{"stem": "tableCloth", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2408), "aabb_size": Vector3(0.9400, 0.3695, 0.5185)},
	{"stem": "tableCoffee", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2077), "aabb_size": Vector3(0.9400, 0.3332, 0.5846)},
	{"stem": "tableCoffeeGlass", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2077), "aabb_size": Vector3(0.9400, 0.3332, 0.5846)},
	{"stem": "tableCoffeeGlassSquare", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.5375, 0.9400)},
	{"stem": "tableCoffeeSquare", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.0300), "aabb_size": Vector3(0.9400, 0.5375, 0.9400)},
	{"stem": "tableCross", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2437), "aabb_size": Vector3(0.9400, 0.3869, 0.5125)},
	{"stem": "tableCrossCloth", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2437), "aabb_size": Vector3(0.9400, 0.3869, 0.5125)},
	{"stem": "tableGlass", "family": "wood", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.2408), "aabb_size": Vector3(0.9400, 0.3695, 0.5185)},
	{"stem": "tableRound", "family": "wood", "walk_through": false, "aabb": Vector3(0.0903, 0.0500, 0.0300), "aabb_size": Vector3(0.8194, 0.4326, 0.9400)},
	{"stem": "televisionAntenna", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3439), "aabb_size": Vector3(0.9400, 0.3695, 0.3122)},
	{"stem": "televisionModern", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.3956), "aabb_size": Vector3(0.9400, 0.6177, 0.2088)},
	{"stem": "televisionVintage", "family": "metal", "walk_through": false, "aabb": Vector3(0.0300, 0.0500, 0.1837), "aabb_size": Vector3(0.9400, 0.6127, 0.6327)},
	{"stem": "toilet", "family": "ceramic", "walk_through": false, "aabb": Vector3(0.1853, 0.0500, 0.0300), "aabb_size": Vector3(0.6295, 0.8706, 0.9400)},
	{"stem": "trashcan", "family": "metal", "walk_through": false, "aabb": Vector3(0.2616, 0.0500, 0.2338), "aabb_size": Vector3(0.4769, 0.9200, 0.5325)},
	{"stem": "washer", "family": "metal", "walk_through": false, "aabb": Vector3(0.1066, 0.0500, 0.1066), "aabb_size": Vector3(0.7868, 0.9200, 0.7868)},
	{"stem": "washerDryerStacked", "family": "metal", "walk_through": false, "aabb": Vector3(0.2933, 0.0500, 0.2933), "aabb_size": Vector3(0.4134, 0.9200, 0.4134)},
]

static func is_prop_id(id: int) -> bool:
	return id >= PROP_FIRST and id <= PROP_LAST


static func index_of(id: int) -> int:
	return id - PROP_FIRST


static func entry(id: int) -> Dictionary:
	var i := index_of(id)
	if i < 0 or i >= ENTRIES.size():
		push_error("RoomPropCatalog.entry: bad id %d" % id)
		return {}
	return ENTRIES[i]


static func stem_of(id: int) -> String:
	var e := entry(id)
	return String(e.get("stem", ""))


static func family_of(id: int) -> String:
	var e := entry(id)
	return String(e.get("family", "wood"))


static func mesh_path(id: int) -> String:
	return PROP_MESH_DIR + stem_of(id) + ".obj"


static func kit_names() -> PackedStringArray:
	var out := PackedStringArray()
	for e in ENTRIES:
		out.append(String(e["stem"]))
	return out


static func find_stem(stem: String) -> int:
	for i in range(ENTRIES.size()):
		if String(ENTRIES[i]["stem"]) == stem:
			return PROP_FIRST + i
	return 0


static func id_for_stem(stem: String) -> int:
	var id := find_stem(stem)
	if id < PROP_FIRST:
		push_error("RoomPropCatalog.id_for_stem: unknown %s" % stem)
		return 0
	return id
