## AUTO-GENERATED by tools/gen_room_prop_catalog.py — do not edit by hand.
## Room prop ID table: VoxelMaterial.PROP_FIRST + index.
class_name RoomPropCatalog
extends RefCounted

const PROP_MESH_DIR := "res://assets/city/props/"
const PROP_FIRST := 75
const PROP_COUNT := 105
const PROP_LAST := 179

## stem, family, walk_through, size (voxel cells), aabb(x,y,z,sx,sy,sz) in voxel units
const ENTRIES: Array[Dictionary] = [
	{"stem": "crate", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0279, 0.0400, 0.0279), "aabb_size": Vector3(0.9443, 1.2157, 0.9443)},
	{"stem": "barrel", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.2200, 0.0600, 0.2200), "aabb_size": Vector3(1.5600, 1.8100, 1.5600)},
	{"stem": "chair", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0715, 0.0400, 0.0715), "aabb_size": Vector3(0.8570, 1.9400, 0.8570)},
	{"stem": "bathroomCabinet", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0200, 0.0400, 0.2200), "aabb_size": Vector3(0.9600, 1.5800, 0.5600)},
	{"stem": "bathroomMirror", "family": "ceramic", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.3389, 0.0400, 0.1728), "aabb_size": Vector3(1.3223, 1.8695, 0.6545)},
	{"stem": "bathroomSink", "family": "ceramic", "walk_through": false, "size": Vector3i(2, 3, 2), "aabb": Vector3(0.2566, 0.0400, 0.3630), "aabb_size": Vector3(1.4868, 2.4030, 1.2740)},
	{"stem": "bathtub", "family": "ceramic", "walk_through": false, "size": Vector3i(6, 2, 3), "aabb": Vector3(0.4481, 0.0400, 0.2885), "aabb_size": Vector3(5.1038, 1.8072, 2.4230)},
	{"stem": "bear", "family": "wood", "walk_through": true, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.1508, 0.0400, 0.4534), "aabb_size": Vector3(1.6983, 1.9349, 1.0932)},
	{"stem": "bedBunk", "family": "fabric", "walk_through": false, "size": Vector3i(3, 4, 5), "aabb": Vector3(0.2651, 0.0400, 0.1502), "aabb_size": Vector3(2.4698, 3.6370, 4.6996)},
	{"stem": "bedDouble", "family": "fabric", "walk_through": false, "size": Vector3i(5, 2, 5), "aabb": Vector3(0.4460, 0.0400, 0.0864), "aabb_size": Vector3(4.1081, 1.6157, 4.8272)},
	{"stem": "bedSingle", "family": "fabric", "walk_through": false, "size": Vector3i(3, 2, 5), "aabb": Vector3(0.2651, 0.0400, 0.0864), "aabb_size": Vector3(2.4698, 1.6157, 4.8272)},
	{"stem": "bench", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.1630, 0.0400, 0.0715), "aabb_size": Vector3(1.6740, 1.9400, 0.8570)},
	{"stem": "benchCushion", "family": "fabric", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.1452, 0.0400, 0.0626), "aabb_size": Vector3(1.7096, 1.9400, 0.8748)},
	{"stem": "benchCushionLow", "family": "fabric", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.1018, 0.0400, 0.0200), "aabb_size": Vector3(1.7964, 0.8564, 0.9600)},
	{"stem": "bookcaseClosed", "family": "wood", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.1289, 0.0400, 0.4481), "aabb_size": Vector3(1.7421, 3.6370, 1.1038)},
	{"stem": "bookcaseClosedDoors", "family": "wood", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.1289, 0.0400, 0.4481), "aabb_size": Vector3(1.7421, 3.6370, 1.1038)},
	{"stem": "bookcaseClosedWide", "family": "wood", "walk_through": false, "size": Vector3i(4, 4, 2), "aabb": Vector3(0.2779, 0.0400, 0.4481), "aabb_size": Vector3(3.4443, 3.3817, 1.1038)},
	{"stem": "bookcaseOpen", "family": "wood", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.1289, 0.0400, 0.4481), "aabb_size": Vector3(1.7421, 3.7647, 1.1038)},
	{"stem": "bookcaseOpenLow", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.1289, 0.0400, 0.4481), "aabb_size": Vector3(1.7421, 1.7221, 1.1038)},
	{"stem": "books", "family": "wood", "walk_through": true, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.1599, 0.0400, 0.2789), "aabb_size": Vector3(0.6802, 0.4621, 0.4421)},
	{"stem": "cabinetBed", "family": "fabric", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.4553, 0.0400, 0.0559), "aabb_size": Vector3(1.0894, 0.9400, 0.8882)},
	{"stem": "cabinetBedDrawer", "family": "fabric", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.4169, 0.0400, 0.0200), "aabb_size": Vector3(1.1662, 1.1343, 0.9600)},
	{"stem": "cabinetBedDrawerTable", "family": "fabric", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.4169, 0.0400, 0.0200), "aabb_size": Vector3(1.1662, 1.1343, 0.9600)},
	{"stem": "cabinetTelevision", "family": "metal", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.2779, 0.0400, 0.4481), "aabb_size": Vector3(3.4443, 1.3391, 1.1038)},
	{"stem": "cabinetTelevisionDoors", "family": "metal", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.2779, 0.0400, 0.4268), "aabb_size": Vector3(3.4443, 1.3391, 1.1464)},
	{"stem": "cardboardBoxOpen", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.1888, 0.0400, 0.0279), "aabb_size": Vector3(1.6224, 1.2157, 0.9443)},
	{"stem": "ceilingFan", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 3), "aabb": Vector3(0.0200, 0.0400, 0.3715), "aabb_size": Vector3(1.9600, 0.5846, 2.2570)},
	{"stem": "chairCushion", "family": "fabric", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0626, 0.0400, 0.0626), "aabb_size": Vector3(0.8748, 1.9400, 0.8748)},
	{"stem": "chairDesk", "family": "wood", "walk_through": false, "size": Vector3i(2, 3, 2), "aabb": Vector3(0.2673, 0.0400, 0.3113), "aabb_size": Vector3(1.4653, 2.6055, 1.3774)},
	{"stem": "chairRounded", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0580, 0.0400, 0.0580), "aabb_size": Vector3(0.8840, 1.9400, 0.8840)},
	{"stem": "coatRack", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.0268, 0.0400, 0.1940), "aabb_size": Vector3(1.9464, 1.2115, 0.6119)},
	{"stem": "coatRackStanding", "family": "wood", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.3996, 0.0400, 0.3996), "aabb_size": Vector3(1.2009, 3.2966, 1.2009)},
	{"stem": "computerKeyboard", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.3796, 0.0400, 0.2285), "aabb_size": Vector3(1.2409, 0.1373, 0.5429)},
	{"stem": "computerMouse", "family": "metal", "walk_through": false, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.3743, 0.0400, 0.2989), "aabb_size": Vector3(0.2515, 0.1203, 0.4021)},
	{"stem": "computerScreen", "family": "metal", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.1445, 0.0400, 0.2587), "aabb_size": Vector3(1.7110, 1.2723, 0.4826)},
	{"stem": "desk", "family": "wood", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.4173, 0.0400, 0.1453), "aabb_size": Vector3(3.1654, 1.6558, 1.7094)},
	{"stem": "deskCorner", "family": "wood", "walk_through": false, "size": Vector3i(5, 2, 5), "aabb": Vector3(0.4066, 0.0400, 0.4066), "aabb_size": Vector3(4.1867, 1.6558, 4.1867)},
	{"stem": "dryer", "family": "metal", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.1834, 0.0400, 0.2038), "aabb_size": Vector3(1.6332, 1.9400, 1.5923)},
	{"stem": "kitchenBar", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.0651, 0.0400, 0.0332), "aabb_size": Vector3(1.8698, 1.8072, 0.9336)},
	{"stem": "kitchenBarEnd", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.2639, 0.0400, 0.0332), "aabb_size": Vector3(0.4722, 1.8072, 0.9336)},
	{"stem": "kitchenBlender", "family": "metal", "walk_through": false, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.2054, 0.0400, 0.2594), "aabb_size": Vector3(0.5892, 0.9400, 0.4812)},
	{"stem": "kitchenCabinet", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.0651, 0.0400, 0.0226), "aabb_size": Vector3(1.8698, 1.9349, 1.9549)},
	{"stem": "kitchenCabinetCornerInner", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.0200, 0.0400, 0.0200), "aabb_size": Vector3(1.9600, 1.8983, 1.9600)},
	{"stem": "kitchenCabinetCornerRound", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.0226, 0.0400, 0.0226), "aabb_size": Vector3(1.9549, 1.9349, 1.9549)},
	{"stem": "kitchenCabinetDrawer1", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.0651, 0.0400, 0.0226), "aabb_size": Vector3(1.8698, 1.9349, 1.9549)},
	{"stem": "kitchenCabinetDrawer", "family": "wood", "walk_through": false, "size": Vector3i(2, 3, 2), "aabb": Vector3(0.0651, 0.0400, 0.2991), "aabb_size": Vector3(1.8698, 2.0275, 1.4017)},
	{"stem": "kitchenCabinetUpper", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.0809, 0.0400, 0.0200), "aabb_size": Vector3(1.8382, 1.6509, 0.9600)},
	{"stem": "kitchenCabinetUpperCorner", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0226, 0.0400, 0.0332), "aabb_size": Vector3(0.9549, 1.6796, 0.9336)},
	{"stem": "kitchenCabinetUpperDouble", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.0809, 0.0400, 0.0200), "aabb_size": Vector3(1.8382, 1.6509, 0.9600)},
	{"stem": "kitchenCabinetUpperLow", "family": "wood", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.0809, 0.0400, 0.0200), "aabb_size": Vector3(1.8382, 0.8355, 0.9600)},
	{"stem": "kitchenCoffeeMachine", "family": "metal", "walk_through": false, "size": Vector3i(1, 1, 2), "aabb": Vector3(0.0767, 0.0400, 0.4690), "aabb_size": Vector3(0.8466, 0.7753, 1.0620)},
	{"stem": "kitchenFridge", "family": "metal", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.0651, 0.0400, 0.3589), "aabb_size": Vector3(1.8698, 3.9349, 1.2823)},
	{"stem": "kitchenFridgeBuiltIn", "family": "metal", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.0651, 0.0400, 0.0226), "aabb_size": Vector3(1.8698, 3.7168, 1.9549)},
	{"stem": "kitchenFridgeSmall", "family": "metal", "walk_through": false, "size": Vector3i(2, 3, 2), "aabb": Vector3(0.0651, 0.0400, 0.3589), "aabb_size": Vector3(1.8698, 2.5742, 1.2823)},
	{"stem": "kitchenMicrowave", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.4000, 0.0400, 0.0200), "aabb_size": Vector3(1.2000, 0.7400, 0.9600)},
	{"stem": "kitchenSink", "family": "ceramic", "walk_through": false, "size": Vector3i(2, 3, 2), "aabb": Vector3(0.0651, 0.0400, 0.0226), "aabb_size": Vector3(1.8698, 2.1051, 1.9549)},
	{"stem": "kitchenStove", "family": "metal", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.0651, 0.0400, 0.0226), "aabb_size": Vector3(1.8698, 1.9349, 1.9549)},
	{"stem": "kitchenStoveElectric", "family": "metal", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.0651, 0.0400, 0.0226), "aabb_size": Vector3(1.8698, 1.9349, 1.9549)},
	{"stem": "lampRoundFloor", "family": "metal", "walk_through": true, "size": Vector3i(1, 4, 1), "aabb": Vector3(0.1565, 0.0400, 0.1065), "aabb_size": Vector3(0.6870, 3.6796, 0.7871)},
	{"stem": "lampRoundTable", "family": "metal", "walk_through": true, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.1565, 0.0400, 0.1065), "aabb_size": Vector3(0.6870, 1.3572, 0.7871)},
	{"stem": "lampSquareCeiling", "family": "metal", "walk_through": true, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.2400, 0.0400, 0.2400), "aabb_size": Vector3(0.5200, 0.9400, 0.5200)},
	{"stem": "lampSquareFloor", "family": "metal", "walk_through": true, "size": Vector3i(1, 4, 1), "aabb": Vector3(0.2247, 0.0400, 0.2247), "aabb_size": Vector3(0.5506, 3.6796, 0.5506)},
	{"stem": "lampSquareTable", "family": "metal", "walk_through": true, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.2247, 0.0400, 0.2247), "aabb_size": Vector3(0.5506, 1.2540, 0.5506)},
	{"stem": "laptop", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 2), "aabb": Vector3(0.4183, 0.0400, 0.4692), "aabb_size": Vector3(1.1634, 0.7086, 1.0616)},
	{"stem": "loungeChair", "family": "wood", "walk_through": false, "size": Vector3i(3, 2, 2), "aabb": Vector3(0.4574, 0.0400, 0.1243), "aabb_size": Vector3(2.0852, 1.9400, 1.7513)},
	{"stem": "loungeChairRelax", "family": "wood", "walk_through": false, "size": Vector3i(3, 3, 3), "aabb": Vector3(0.4374, 0.0400, 0.0445), "aabb_size": Vector3(2.1251, 2.7009, 2.9110)},
	{"stem": "loungeSofa", "family": "fabric", "walk_through": false, "size": Vector3i(5, 2, 2), "aabb": Vector3(0.4348, 0.0400, 0.1243), "aabb_size": Vector3(4.1304, 1.9400, 1.7513)},
	{"stem": "loungeSofaCorner", "family": "fabric", "walk_through": false, "size": Vector3i(5, 2, 5), "aabb": Vector3(0.4348, 0.0400, 0.4348), "aabb_size": Vector3(4.1304, 1.9400, 4.1304)},
	{"stem": "loungeSofaLong", "family": "fabric", "walk_through": false, "size": Vector3i(5, 2, 4), "aabb": Vector3(0.4348, 0.0400, 0.2687), "aabb_size": Vector3(4.1304, 1.9400, 3.4626)},
	{"stem": "loungeSofaOttoman", "family": "fabric", "walk_through": false, "size": Vector3i(2, 1, 2), "aabb": Vector3(0.1003, 0.0400, 0.0800), "aabb_size": Vector3(1.7993, 0.9400, 1.8400)},
	{"stem": "pillow", "family": "fabric", "walk_through": true, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.0200, 0.0400, 0.3030), "aabb_size": Vector3(0.9600, 0.9087, 0.3939)},
	{"stem": "pillowLong", "family": "fabric", "walk_through": true, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.1796, 0.0400, 0.2968), "aabb_size": Vector3(1.6409, 0.9400, 0.4064)},
	{"stem": "plantSmall1", "family": "foliage", "walk_through": true, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.2786, 0.0400, 0.2786), "aabb_size": Vector3(0.4428, 0.6157, 0.4428)},
	{"stem": "plantSmall2", "family": "foliage", "walk_through": true, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.2786, 0.0400, 0.2786), "aabb_size": Vector3(0.4428, 0.6157, 0.4428)},
	{"stem": "plantSmall3", "family": "foliage", "walk_through": true, "size": Vector3i(1, 1, 1), "aabb": Vector3(0.2715, 0.0400, 0.2994), "aabb_size": Vector3(0.4570, 0.6370, 0.4012)},
	{"stem": "pottedPlant", "family": "foliage", "walk_through": true, "size": Vector3i(1, 3, 2), "aabb": Vector3(0.0288, 0.0400, 0.4663), "aabb_size": Vector3(0.9424, 2.8031, 1.0675)},
	{"stem": "radio", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.3450, 0.0400, 0.2835), "aabb_size": Vector3(1.3100, 0.9400, 0.4331)},
	{"stem": "rugRectangle", "family": "fabric", "walk_through": true, "size": Vector3i(6, 1, 4), "aabb": Vector3(0.0200, 0.0400, 0.2455), "aabb_size": Vector3(5.9600, 0.0577, 3.5090)},
	{"stem": "rugRound", "family": "fabric", "walk_through": true, "size": Vector3i(4, 1, 4), "aabb": Vector3(0.0226, 0.0400, 0.0226), "aabb_size": Vector3(3.9549, 0.0626, 3.9549)},
	{"stem": "rugRounded", "family": "fabric", "walk_through": true, "size": Vector3i(6, 1, 4), "aabb": Vector3(0.0200, 0.0400, 0.2455), "aabb_size": Vector3(5.9600, 0.0577, 3.5090)},
	{"stem": "rugSquare", "family": "fabric", "walk_through": true, "size": Vector3i(4, 1, 4), "aabb": Vector3(0.0559, 0.0400, 0.0226), "aabb_size": Vector3(3.8882, 0.0626, 3.9549)},
	{"stem": "shower", "family": "ceramic", "walk_through": false, "size": Vector3i(3, 5, 3), "aabb": Vector3(0.2847, 0.0400, 0.2421), "aabb_size": Vector3(2.4306, 4.6755, 2.5157)},
	{"stem": "sideTable", "family": "wood", "walk_through": false, "size": Vector3i(3, 2, 1), "aabb": Vector3(0.3625, 0.0400, 0.0200), "aabb_size": Vector3(2.2751, 1.6275, 0.9600)},
	{"stem": "sideTableDrawers", "family": "wood", "walk_through": false, "size": Vector3i(3, 2, 1), "aabb": Vector3(0.3740, 0.0400, 0.0200), "aabb_size": Vector3(2.2520, 1.6109, 0.9600)},
	{"stem": "speaker", "family": "metal", "walk_through": false, "size": Vector3i(1, 3, 1), "aabb": Vector3(0.1651, 0.0400, 0.1651), "aabb_size": Vector3(0.6698, 2.7281, 0.6698)},
	{"stem": "speakerSmall", "family": "metal", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.1651, 0.0400, 0.1966), "aabb_size": Vector3(0.6698, 1.2880, 0.6068)},
	{"stem": "stoolBar", "family": "wood", "walk_through": false, "size": Vector3i(2, 2, 1), "aabb": Vector3(0.4488, 0.0400, 0.0200), "aabb_size": Vector3(1.1023, 1.7609, 0.9600)},
	{"stem": "stoolBarSquare", "family": "wood", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.1534, 0.0400, 0.1659), "aabb_size": Vector3(0.6932, 1.7434, 0.6682)},
	{"stem": "table", "family": "wood", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.1896, 0.0400, 0.0281), "aabb_size": Vector3(3.6208, 1.4104, 1.9437)},
	{"stem": "tableCloth", "family": "wood", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.1896, 0.0400, 0.0281), "aabb_size": Vector3(3.6208, 1.4104, 1.9437)},
	{"stem": "tableCoffee", "family": "metal", "walk_through": false, "size": Vector3i(3, 1, 2), "aabb": Vector3(0.1580, 0.0400, 0.1800), "aabb_size": Vector3(2.6840, 0.9400, 1.6400)},
	{"stem": "tableCoffeeGlass", "family": "metal", "walk_through": false, "size": Vector3i(3, 1, 2), "aabb": Vector3(0.1580, 0.0400, 0.1800), "aabb_size": Vector3(2.6840, 0.9400, 1.6400)},
	{"stem": "tableCoffeeGlassSquare", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 2), "aabb": Vector3(0.1800, 0.0400, 0.1800), "aabb_size": Vector3(1.6400, 0.9400, 1.6400)},
	{"stem": "tableCoffeeSquare", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 2), "aabb": Vector3(0.1800, 0.0400, 0.1800), "aabb_size": Vector3(1.6400, 0.9400, 1.6400)},
	{"stem": "tableCross", "family": "wood", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.1670, 0.0400, 0.0281), "aabb_size": Vector3(3.6660, 1.4984, 1.9437)},
	{"stem": "tableCrossCloth", "family": "wood", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.1670, 0.0400, 0.0281), "aabb_size": Vector3(3.6660, 1.4984, 1.9437)},
	{"stem": "tableGlass", "family": "wood", "walk_through": false, "size": Vector3i(4, 2, 2), "aabb": Vector3(0.1896, 0.0400, 0.0281), "aabb_size": Vector3(3.6208, 1.4104, 1.9437)},
	{"stem": "tableRound", "family": "wood", "walk_through": false, "size": Vector3i(3, 2, 4), "aabb": Vector3(0.0200, 0.0400, 0.2941), "aabb_size": Vector3(2.9600, 1.5657, 3.4117)},
	{"stem": "televisionAntenna", "family": "metal", "walk_through": false, "size": Vector3i(2, 1, 1), "aabb": Vector3(0.4172, 0.0400, 0.3098), "aabb_size": Vector3(1.1657, 0.4572, 0.3804)},
	{"stem": "televisionModern", "family": "metal", "walk_through": false, "size": Vector3i(3, 2, 1), "aabb": Vector3(0.0344, 0.0400, 0.2089), "aabb_size": Vector3(2.9313, 1.9400, 0.5821)},
	{"stem": "televisionVintage", "family": "metal", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.1077, 0.0400, 0.4055), "aabb_size": Vector3(1.7847, 1.1689, 1.1889)},
	{"stem": "toilet", "family": "ceramic", "walk_through": false, "size": Vector3i(2, 2, 3), "aabb": Vector3(0.3150, 0.0400, 0.4647), "aabb_size": Vector3(1.3700, 1.9390, 2.0705)},
	{"stem": "trashcan", "family": "metal", "walk_through": false, "size": Vector3i(1, 2, 1), "aabb": Vector3(0.0719, 0.0400, 0.0200), "aabb_size": Vector3(0.8561, 1.7013, 0.9600)},
	{"stem": "washer", "family": "metal", "walk_through": false, "size": Vector3i(2, 2, 2), "aabb": Vector3(0.1834, 0.0400, 0.1834), "aabb_size": Vector3(1.6332, 1.9400, 1.6332)},
	{"stem": "washerDryerStacked", "family": "metal", "walk_through": false, "size": Vector3i(2, 4, 2), "aabb": Vector3(0.1668, 0.0400, 0.1668), "aabb_size": Vector3(1.6664, 3.9400, 1.6664)},
]

static func is_prop_id(id: int) -> bool:
	return id >= PROP_FIRST and id <= PROP_LAST


static func index_of(id: int) -> int:
	return id - PROP_FIRST


static func entry(id: int) -> Dictionary:
	var i := index_of(id)
	if i < 0 or i >= ENTRIES.size():
		push_error("RoomPropCatalog.entry: bad id %d" % id)
		return {}
	return ENTRIES[i]


static func stem_of(id: int) -> String:
	var e := entry(id)
	return String(e.get("stem", ""))


static func family_of(id: int) -> String:
	var e := entry(id)
	return String(e.get("family", "wood"))


static func size_of_id(id: int) -> Vector3i:
	var e := entry(id)
	return e.get("size", Vector3i.ONE) as Vector3i


static func size_of_stem(stem: String) -> Vector3i:
	var id := find_stem(stem)
	if id < PROP_FIRST:
		return Vector3i.ONE
	return size_of_id(id)


static func mesh_path(id: int) -> String:
	return PROP_MESH_DIR + stem_of(id) + ".obj"


static func kit_names() -> PackedStringArray:
	var out := PackedStringArray()
	for e in ENTRIES:
		out.append(String(e["stem"]))
	return out


static func find_stem(stem: String) -> int:
	for i in range(ENTRIES.size()):
		if String(ENTRIES[i]["stem"]) == stem:
			return PROP_FIRST + i
	return 0


static func id_for_stem(stem: String) -> int:
	var id := find_stem(stem)
	if id < PROP_FIRST:
		push_error("RoomPropCatalog.id_for_stem: unknown %s" % stem)
		return 0
	return id
